In [12]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# 활성화 함수 구현
# 1. 계단 함수
# 2. 시그모이드 함수 
# 3. ReLU 함수 

In [23]:
# 1. 계단 함수

def step_function(x):
    return np.where(x > 0, 1, 0)

In [26]:
x = np.array([5.0, -5.0, 1.0])
y = step_function(x)
y

array([1, 0, 1])

In [29]:
# 2. 시그모이드 함수 

def sigmoid(x):
    return 1 / (1 + np.exp(x))

In [33]:
x = np.array([5.0, -5.0, 1.0])
y = sigmoid(x)
y

array([0.00669285, 0.99330715, 0.26894142])

In [37]:
# 3. ReLU 함수

def ReLU(x):
    return np.maximum(0, x)
    return np.where(x>0, x,0)

In [42]:
x = np.array([5.0, -5.0, 1.0])
y = ReLU(x)
y

array([5., 0., 1.])

In [54]:
# 3층 신경망 구성하기

x = np.array([1,2]) # 1 x 2
w = np.array([[1,3,5],[2,4,6]]) # 2 x 3

# np.dot(x,w)
x@w

array([ 5, 11, 17])

In [72]:
# 3층 신경망 구현하기
class Net():
    def __init__(self):
        self.network ={}
        self.network['w1'] = np.array([[0.1, 0.3, 0.5],[0.2, 0.4, 0.6]])
        self.network['b1'] = np.array([0.1, 0.2, 0.3])
                                       
        self.network['w2'] = np.array([[0.1, 0.4],[0.2, 0.5],[0.3, 0.6]])        
        self.network['b2'] = np.array([0.1, 0.2])  
        
        self.network['w3'] = np.array([[0.1, 0.3],[0.2, 0.4]])        
        self.network['b3'] = np.array([0.1, 0.2])
        
    def identity_function(self, x):
        return x
    
    def sigmoid(self, x):
        return 1 / (1 + np.exp(x)) 
    
    def forward(self, x):
        w1, w2, w3 = self.network['w1'], self.network['w2'], self.network['w3']
        b1, b2, b3 = self.network['b1'], self.network['b2'], self.network['b3']
        
        a1 = np.dot(x, w1) + b1
        z1 = self.sigmoid(a1)
        a2 = np.dot(z1, w2) + b2
        z2 = self.sigmoid(a2)
        a3 = np.dot(z2, w3) + b3
        y = self.identity_function(a3)
        
        return y
        

In [74]:
net = Net()
x = np.array([1.0,2.0])
net.forward(x)

array([0.21922409, 0.48311781])

In [77]:
# 소프트맥스 구현
def softmax(x):
    c = np.max(x)
    exp_x = np.exp(x - c)
    exp_all = np.sum(exp_x)
    return exp_x / exp_all

In [78]:
a = np.array([0.3, 2.9, 4.0])
softmax(a)

array([0.01821127, 0.24519181, 0.73659691])

In [80]:
np.sum(softmax(a))

1.0

In [ ]:
# mnist를 이용한 신경망 구현

In [114]:
from dataset03.dataset.mnist import load_mnist

In [116]:
weight_dir = './dataset03/sample_weight.pkl'

In [165]:
import pickle

class MnistModel():
    
    def __init__(self, weight_dir):
        with open(weight_dir, 'rb') as f:
            self.network = pickle.load(f)
            
    def get_data(self):
        (x_train, t_train), (x_test, t_test) = load_mnist(flatten=True, normalize=False)
        return (x_train, t_train), (x_test, t_test)
    
    def predict(self, x):
        W1, W2, W3 = self.network['W1'], self.network['W2'], self.network['W3']
        b1, b2, b3 = self.network['b1'], self.network['b2'], self.network['b3']
        
        a1 = np.dot(x, W1) + b1
        z1 = sigmoid(a1)
        a2 = np.dot(z1,W2) + b2
        z2 = sigmoid(a2)
        a3 = np.dot(z2, W3) + b3
        y = softmax(a3)
        
        return y
    
    def accurancy(self, x, y):
        
        accuracy_cnt = 0
        
        for i in range(len(x)):
            if np.argmax(self.predict(x[i])) == y[i]:
                accuracy_cnt += 1
        
        print(f"Accuracy : {float(accuracy_cnt) / len(x)}")
        
    def accuracy_cnt_batch(self, x, t, batch_size):
        
        accuracy_cnt = 0
        
        for i in range(0 , len(x) , batch_size) :
            x_batch = x [i:i+batch_size]
            y_batch = self.predict(x_batch)
            p = np.argmax(y_batch, axis=1)
            accuracy_cnt = accuracy_cnt + np.sum(p == t[i:i+batch_size])
            
        print(f"Accuracy : {float(accuracy_cnt) / len(x)}") 

In [166]:
model = MnistModel(weight_dir)

(x1, t1), (x, t)  = model.get_data()
model.accurancy(x,t)

C:\Users\dudwl\AppData\Local\Temp/ipykernel_14448/2587523294.py:4: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(x))


Accuracy : 0.8399


In [167]:
model.accuracy_cnt_batch(x,t,100)

Accuracy : 0.8399


C:\Users\dudwl\AppData\Local\Temp/ipykernel_14448/2587523294.py:4: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(x))
