In [5]:
import numpy as np

In [6]:
A = np.array([1 , 2, 3, 4])

In [7]:
np.ndim(A)

1

In [8]:
A.shape

(4,)

In [9]:
A.shape[0]

4

In [10]:
B = np.array([[1 , 2], [3 , 4], [5 , 6]])

In [11]:
np.ndim(B)

2

In [12]:
B.shape

(3, 2)

In [13]:
A = np.array([[1 , 2], (3, 4)])

In [14]:
B = np.array([[5 , 6], [7 , 8]])

np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [15]:
X = np.array([1,2]) 
print(X)
W = np.array([[1,3,5],[2,4,6]])
print(W)
Y = np.dot(X, W)
Y

[1 2]
[[1 3 5]
 [2 4 6]]


array([ 5, 11, 17])

In [16]:
Y

array([ 5, 11, 17])